[package]
name = "furtherance"
version = "1.4.0"
authors = ["Ricky Kresslein <rk@lakoliu.com>"]
edition = "2018"

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
rusqlite = "0.27.0"
chrono = "0.4"
directories = "4.0"
once_cell = "1.12.0"
dbus = "0.9.5"
dbus-codegen = "0.10.0"
log = "0.4"
gtk4-macros = "0.4.8"
itertools = "0.10.3"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
csv = "1.1.6"
num-traits = "0.2.14"
num-derive = "0.3.3"

[dependencies.gtk]
package = "gtk4"
version = "0.4.8"

[dependencies.adw]
package = "libadwaita"
version = "0.1.1"
