[package]
name = "furtherance"
version = "1.0.9"
authors = ["Ricky Kresslein <rk@lakoliu.com>"]
edition = "2018"

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
rusqlite = "0.26.3"
chrono = "0.4"
directories = "4.0"
once_cell = "1.9.0"
dbus = "0.9.5"
dbus-codegen = "0.10.0"

[dependencies.gtk]
package = "gtk4"
version = "0.4"

[dependencies.adw]
package = "libadwaita"
version = "0.1"

