[package]
name = "furtherance"
version = "1.5.2"
authors = ["Ricky Kresslein <rk@lakoliu.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["unstable-locales"] }
chrono_locale = "0.1"
csv = "1.1.6"
dbus = "0.9.5"
dbus-codegen = "0.10.0"
directories = "4.0"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk4-macros = "0.4.8"
itertools = "0.10.3"
log = "0.4"
num-derive = "0.3.3"
num-traits = "0.2.14"
once_cell = "1.12.0"
rusqlite = "0.27.0"
serde = { version = "1.0", features = ["derive"] }

[dependencies.gtk]
package = "gtk4"
version = "0.4.8"

[dependencies.adw]
package = "libadwaita"
version = "0.1.1"
