[package]
name = "furtherance"
version = "3.0.0"
authors = ["Ricky Kresslein <ricky@unobserved.io>"]
edition = "2021"

[dependencies]
config = "0.14"
chrono = { version = "0.4", features = ["alloc", "serde"] }
dark-light = "1.0"
directories = "5.0"
iced = { version = "0.12", features = [
    "advanced",
    "canvas",
    "multi-window",
    "tokio",
] }
iced_aw = { version = "0.9", default-features = false, features = [
    "card",
    "date_picker",
    "icons",
    "modal",
    "time_picker",
] }
plotters = "0.3"
plotters-iced = "0.10"
regex = "1.10"
rusqlite = { version = "0.32.0", features = ["bundled", "chrono", "backup"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
tokio = "1.39"
user-idle = "0.6.0"
users = "0.11.0"
zbus = "4.4"

[target.'cfg(target_os = "linux")'.dependencies]
x11rb = "0.13.1"
